const website_list = [
    {"name": "Google", "url": "https://www.google.com"},
    {"name": "YouTube", "url": "https://www.youtube.com"},
    {"name": "Facebook", "url": "https://www.facebook.com"},
    {"name": "Twitter", "url": "https://twitter.com"},
    {"name": "Instagram", "url": "https://www.instagram.com"},
    {"name": "Reddit", "url": "https://www.reddit.com"},
    {"name": "Amazon", "url": "https://www.amazon.com"},
    {"name": "Netflix", "url": "https://www.netflix.com"},
    {"name": "LinkedIn", "url": "https://www.linkedin.com"},
    {"name": "Wikipedia", "url": "https://www.wikipedia.org"},
    {"name": "Dropbox", "url": "https://www.dropbox.com"},
    {"name": "Spotify", "url": "https://www.spotify.com"},
    {"name": "Pinterest", "url": "https://www.pinterest.com"},
    {"name": "Tumblr", "url": "https://www.tumblr.com"},
    {"name": "GitHub", "url": "https://github.com"},
    {"name": "Medium", "url": "https://medium.com"},
    {"name": "Quora", "url": "https://www.quora.com"},
    {"name": "Stack Overflow", "url": "https://stackoverflow.com"},
    {"name": "Snapchat", "url": "https://www.snapchat.com"},
    {"name": "WhatsApp", "url": "https://www.whatsapp.com"},
    {"name": "Twitch", "url": "https://www.twitch.tv"},
    {"name": "CNN", "url": "https://www.cnn.com"},
    {"name": "BBC News", "url": "https://www.bbc.com/news"},
    {"name": "Hulu", "url": "https://www.hulu.com"},
    {"name": "BuzzFeed", "url": "https://www.buzzfeed.com"},
    {"name": "National Geographic", "url": "https://www.nationalgeographic.com"},
    {"name": "TED", "url": "https://www.ted.com"},
    {"name": "Alibaba", "url": "https://www.alibaba.com"},
    {"name": "The Guardian", "url": "https://www.theguardian.com"},
    {"name": "Adobe", "url": "https://www.adobe.com"},
    {"name": "NBA", "url": "https://www.nba.com"},
    {"name": "NASA", "url": "https://www.nasa.gov"},
    {"name": "Economist", "url": "https://www.economist.com"},
    {"name": "WordPress", "url": "https://www.wordpress.org"},
    {"name": "Zillow", "url": "https://www.zillow.com"},
    {"name": "Harvard University", "url": "https://www.harvard.edu"},
    {"name": "Merriam-Webster", "url": "https://www.merriam-webster.com"},
    {"name": "Flickr", "url": "https://www.flickr.com"},
    {"name": "Trello", "url": "https://trello.com"},
    {"name": "Etsy", "url": "https://www.etsy.com"},
    {"name": "Vimeo", "url": "https://vimeo.com"},
    {"name": "CNN Business", "url": "https://www.cnn.com/business"},
    {"name": "Smithsonian", "url": "https://www.si.edu"},
    {"name": "ArXiv", "url": "https://arxiv.org"},
    {"name": "Atlas Obscura", "url": "https://www.atlasobscura.com"},
    {"name": "TED Talks", "url": "https://www.ted.com/tedx"},
    {"name": "JSTOR", "url": "https://www.jstor.org"},
    {"name": "Gutenberg Project", "url": "https://www.gutenberg.org"},
    {"name": "The Onion", "url": "https://www.theonion.com"},
    {"name": "The Atlantic", "url": "https://www.theatlantic.com"},
    {"name": "Last.fm", "url": "https://www.last.fm"},
    {"name": "MyFitnessPal", "url": "https://www.myfitnesspal.com"},
    {"name": "Bored Panda", "url": "https://www.boredpanda.com"},
    {"name": "HowStuffWorks", "url": "https://www.howstuffworks.com"},
    {"name": "JPL NASA", "url": "https://www.jpl.nasa.gov"},
    {"name": "Investopedia", "url": "https://www.investopedia.com"},
    {"name": "Dictionary.com", "url": "https://www.dictionary.com"},
    {"name": "National Geographic Kids", "url": "https://kids.nationalgeographic.com"},
    {"name": "PBS", "url": "https://www.pbs.org"},
    {"name": "FIFA", "url": "https://www.fifa.com"},
    {"name": "Hackaday", "url": "https://hackaday.com"},
    {"name": "The Smithsonian's National Air and Space Museum", "url": "https://airandspace.si.edu"},
    {"name": "World Health Organization", "url": "https://www.who.int"},
    {"name": "Yahoo! Japan", "url": "https://www.yahoo.co.jp"},
    {"name": "楽天市場", "url": "https://www.rakuten.co.jp"},
    {"name": "Amazon Japan", "url": "https://www.amazon.co.jp"},
    {"name": "AbemaTV", "url": "https://abema.tv"},
    {"name": "LINE", "url": "https://line.me/ja/"},
    {"name": "ニコニコ動画", "url": "https://www.nicovideo.jp"},
    {"name": "ヤフオク!", "url": "https://auctions.yahoo.co.jp"},
    {"name": "東京都公式ウェブサイト", "url": "https://www.metro.tokyo.lg.jp"},
    {"name": "JR東日本", "url": "https://www.jreast.co.jp"},
    {"name": "Gunosy", "url": "https://gunosy.com"},
    {"name": "マクドナルド", "url": "https://www.mcdonalds.co.jp"},
    {"name": "ANA", "url": "https://www.ana.co.jp"},
    {"name": "DMM.com", "url": "https://www.dmm.com"},
    {"name": "セブン-イレブン", "url": "https://www.sej.co.jp"},
    {"name": "楽天トラベル", "url": "https://travel.rakuten.co.jp"},
    {"name": "日本テレビ", "url": "https://www.ntv.co.jp"},
    {"name": "サントリー", "url": "https://www.suntory.co.jp"},
    {"name": "電通", "url": "https://www.dentsu.co.jp"},
    {"name": "サッポロビール", "url": "https://www.sapporobeer.jp"},
    {"name": "SoftBank", "url": "https://www.softbank.jp"},
    {"name": "NTTドコモ", "url": "https://www.nttdocomo.co.jp"},
    {"name": "Toyota", "url": "https://www.toyota.co.jp"},
    {"name": "Honda", "url": "https://www.honda.co.jp"},
    {"name": "Sony", "url": "https://www.sony.co.jp"},
    {"name": "Panasonic", "url": "https://www.panasonic.co.jp"},
    {"name": "Nintendo", "url": "https://www.nintendo.co.jp"},
    {"name": "Shiseido", "url": "https://www.shiseido.co.jp"},
    {"name": "Uniqlo", "url": "https://www.uniqlo.com/jp"},
    {"name": "ANA", "url": "https://www.ana.co.jp"},
    {"name": "JAL", "url": "https://www.jal.co.jp"},
    {"name": "GMOペパボ", "url": "https://pepabo.com"},
    {"name": "Naverまとめ", "url": "https://matome.naver.jp"},
    {"name": "ニフティニュース", "url": "https://news.nifty.com"},
    {"name": "富士通", "url": "https://www.fujitsu.com/jp"},
    {"name": "ハウス食品", "url": "https://www.housefoods.jp"},
    {"name": "ライソケ", "url": "https://lifull.com"},
    {"name": "ZOZOTOWN", "url": "https://zozo.jp"},
    {"name": "レアジョブ英会話", "url": "https://www.rarejob.com"},
    {"name": "RIZAP", "url": "https://www.rizap.jp"}
  ]
  